server:
 port:
  ":8080"
db:
    host:
        suleiman.db.elephantsql.com
    port:
        5432
    database:
        dcifyomf
    user:
        dcifyomf
    password:
        86TOywz5oPrR4phxByspk876_hfm9lK4
    sslmode:
        disable
    maxIdleConns:
        5 
    maxOpenConns:
        5
    driver:
        postgres
